# Generated by Django 5.0.2 on 2024-05-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('completion_state', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
